version: "3.9"

services:
  nginx:
    build:
      context: .
      dockerfile: .infrastructure/nginx/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./.infrastructure/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - service

  service:
    build:
      context: .
      dockerfile: .infrastructure/service/Dockerfile
    command: bash
    volumes:
      - .:/app:cached
    ports:
      - "8080:8080"
      - "2112:2112"
